### ISSUE TITLE
Static initialization order fiasco problem

### ISSUE THREAD

**Issue by fpalita** [tnakagome/exray#1]
exray::Options::outputFilters is a static variable and it is used by the ExceptionHandler to try and filter exceptions. 

Now if the using application throws from another static initialization, if outputFilters wasn't yet initialized, the application will crash. (there's a 50/50 chance)

In my case it crashed. I fixed it by making outputFilters a static function instead (which just creates a static object and returns its reference). This fixes the above problem.

**Comment by tnakagome** [comment]
Thanks for your feedback. I have not encountered that issue before on this particular library, but I am familiar with the phenomenon.

If you could give me the diff, I will try to apply it when I have time.

**Comment by fpalita** [comment]
Sure, I've attached the diff for the 3 files.


[Options.cpp.diff.txt](https://github.com/tnakagome/exray/files/741865/Options.cpp.diff.txt)
[Options.h.diff.txt](https://github.com/tnakagome/exray/files/741866/Options.h.diff.txt)
[ExceptionHandler.cpp.diff.txt](https://github.com/tnakagome/exray/files/741867/ExceptionHandler.cpp.diff.txt)

**Comment by tnakagome** [comment]
Great. Thanks! Will look into it in my spare time.

**Comment by tnakagome** [comment]
Integrated the patch. Thanks fpalita.
